import { useEffect, useRef, useState, type MouseEvent, type ReactNode } from "react";
import { AnimatePresence, motion, useInView, useReducedMotion, useScroll, useSpring, useTransform } from "motion/react";
import { ArrowDown, ArrowRight, CalendarDays, ChevronDown, Clock3, Cloud, Code2, ExternalLink, Facebook, Github, Instagram, Linkedin, Mail, MapPin, Menu, Mountain, Network, Phone, UserRound, X } from "lucide-react";
import communityImage from "@/assets/past-community.jpg";
import workshopImage from "@/assets/past-workshop.jpg";
import { clubs, event, faqs, footerContent, navItems, partnerGroups, pastEvents, schedule, socialLinks, speakers, stats, team } from "@/data/content";

const sectionMotion = { initial: { opacity: 0, y: 38, filter: "blur(8px)" }, whileInView: { opacity: 1, y: 0, filter: "blur(0px)" }, viewport: { once: true, margin: "-80px" }, transition: { duration: .75, ease: [0.22, 1, 0.36, 1] as const } };

function BrandMark({ compact = false }: { compact?: boolean }) {
  return <a href="#home" className="brand" aria-label="AWS Student Community Day Pokhara home"><span className="brand-cloud"><Cloud /></span><span className={compact ? "sr-only" : "brand-copy"}><strong>AWS Student</strong><small>Community Day · Pokhara</small></span></a>;
}

function SocialLinks({ light = false }: { light?: boolean }) {
  return <div className={`socials ${light ? "socials-light" : ""}`}><a href={socialLinks.linkedin} target="_blank" rel="noreferrer" aria-label="Visit LinkedIn"><Linkedin /></a><a href={socialLinks.github} target="_blank" rel="noreferrer" aria-label="Visit GitHub"><Github /></a><a href={socialLinks.x} target="_blank" rel="noreferrer" aria-label="Visit X"><span>𝕏</span></a></div>;
}

function Reveal({ children, className = "" }: { children: ReactNode; className?: string }) {
  return <motion.div {...sectionMotion} className={className}>{children}</motion.div>;
}

function SectionHeading({ label, title, accent, light = false, align = "left" }: { label: string; title: string; accent?: string; light?: boolean; align?: "left" | "center" }) {
  return <div className={`section-heading ${light ? "on-light" : ""} ${align === "center" ? "text-center" : ""}`}><p className="eyebrow"><span>⌁</span> {label}</p><h2>{title} {accent && <em>{accent}</em>}</h2></div>;
}

function Navbar() {
  const [open, setOpen] = useState(false);
  const [active, setActive] = useState("home");
  const [scrolled, setScrolled] = useState(false);
  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 32);
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) setActive(entry.target.id); }), { rootMargin: "-35% 0px -55%", threshold: 0 });
    navItems.forEach(([, id]) => { const node = document.getElementById(id); if (node) observer.observe(node); });
    window.addEventListener("scroll", onScroll, { passive: true }); onScroll();
    return () => { observer.disconnect(); window.removeEventListener("scroll", onScroll); };
  }, []);
  return <header className={`navbar ${scrolled ? "is-scrolled" : ""}`}><div className="nav-inner"><BrandMark /><nav className="desktop-nav" aria-label="Primary navigation">{navItems.map(([label, id]) => <a key={id} href={`#${id}`} className={active === id ? "active" : ""}>{label}</a>)}</nav><div className="nav-actions"><a className="button button-primary button-small" href={event.meetupUrl} target="_blank" rel="noreferrer">Register <ArrowRight /></a><button className="menu-button" aria-label="Open menu" aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div></div><AnimatePresence>{open && <motion.nav className="mobile-nav" initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} exit={{ opacity: 0, height: 0 }} aria-label="Mobile navigation">{navItems.map(([label, id], i) => <motion.a initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * .035 }} key={id} href={`#${id}`} onClick={() => setOpen(false)}><span>0{i + 1}</span>{label}</motion.a>)}</motion.nav>}</AnimatePresence></header>;
}

function Hero() {
  const { scrollY } = useScroll();
  const reduce = useReducedMotion();
  const copyY = useTransform(scrollY, [0, 800], [0, reduce ? 0 : 90]);
  const moveField = (e: MouseEvent<HTMLElement>) => {
    if (reduce) return;
    const bounds = e.currentTarget.getBoundingClientRect();
    e.currentTarget.style.setProperty("--mouse-x", `${e.clientX - bounds.left}px`);
    e.currentTarget.style.setProperty("--mouse-y", `${e.clientY - bounds.top}px`);
    e.currentTarget.style.setProperty("--drift-x", `${((e.clientX - bounds.left) / bounds.width - .5) * 28}px`);
    e.currentTarget.style.setProperty("--drift-y", `${((e.clientY - bounds.top) / bounds.height - .5) * 20}px`);
  };
  const nodes = Array.from({ length: 24 }, (_, i) => ({ left: `${7 + ((i * 37) % 88)}%`, top: `${10 + ((i * 53) % 76)}%`, delay: `${(i % 7) * .2}s` }));
  return <section id="home" className="hero" onMouseMove={moveField}><div className="hero-grid" aria-hidden="true"/><div className="cursor-aura" aria-hidden="true"/><div className="network-field" aria-hidden="true">{nodes.map((node,i) => <span key={i} style={{ left: node.left, top: node.top, animationDelay: node.delay }} />)}<i className="network-orbit orbit-one"/><i className="network-orbit orbit-two"/></div><div className="mountain-lines" aria-hidden="true"><i/><i/><i/><i/></div><motion.div className="hero-content shell" style={{ y: copyY }}><motion.div className="hero-kicker" initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .2 }}><span className="live-dot" /> Nepal’s student cloud gathering <span>／ 2026</span></motion.div><motion.h1 initial={{ opacity: 0, y: 42 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .9, delay: .3 }}><span>AWS Student</span><span>Community Day</span><strong>POKHARA</strong></motion.h1><motion.div className="hero-bottom" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .8 }}><div><p className="tagline">{event.tagline}</p><div className="event-meta"><span><CalendarDays /> {event.dateLabel}</span><span><MapPin /> {event.venue}</span></div></div><div className="hero-ctas"><a className="button button-primary magnetic" href={event.meetupUrl} target="_blank" rel="noreferrer">Register now <ArrowRight /></a><a className="button button-ghost" href="#call-for-speakers">Become a speaker</a></div></motion.div></motion.div><a href="#about" className="scroll-cue"><span>Scroll to explore</span><ArrowDown /></a><div className="hero-coordinates">28.2096° N<br/>83.9856° E</div></section>;
}

function CountUp({ value, suffix }: { value: number; suffix: string }) {
  const ref = useRef<HTMLSpanElement>(null); const visible = useInView(ref, { once: true }); const [count, setCount] = useState(0);
  useEffect(() => { if (!visible) return; let frame = 0; const start = performance.now(); const tick = (now: number) => { const p = Math.min((now-start)/1400,1); setCount(Math.round(value*(1-Math.pow(1-p,3)))); if(p<1) frame=requestAnimationFrame(tick); }; frame=requestAnimationFrame(tick); return () => cancelAnimationFrame(frame); }, [visible,value]);
  return <span ref={ref}>{count}{suffix}</span>;
}

function TiltCard({ children, className = "" }: { children: ReactNode; className?: string }) {
  const reduce = useReducedMotion(); const onMove = (e: MouseEvent<HTMLDivElement>) => { if(reduce) return; const el=e.currentTarget; const r=el.getBoundingClientRect(); const x=(e.clientX-r.left)/r.width; const y=(e.clientY-r.top)/r.height; el.style.setProperty("--rx", `${(0.5-y)*7}deg`); el.style.setProperty("--ry", `${(x-0.5)*7}deg`); el.style.setProperty("--gx", `${x*100}%`); el.style.setProperty("--gy", `${y*100}%`); };
  return <div className={`tilt ${className}`} onMouseMove={onMove} onMouseLeave={(e)=>{e.currentTarget.style.setProperty("--rx","0deg");e.currentTarget.style.setProperty("--ry","0deg");}}>{children}</div>;
}

function About() { return <section id="about" className="section about"><div className="shell"><Reveal className="about-intro"><SectionHeading label="01 — About the day" title="Where curiosity meets" accent="cloud scale." /><p className="lead">A one-day collision of bold ideas, practical skills, and the people shaping Nepal’s cloud future.</p><div className="terminal"><div><i/><i/><i/><span>builders@pokhara:~</span></div><code>$ deploy curiosity --region ap-south-1<br/><b>✓</b> 500 builders connected</code></div></Reveal><Reveal className="stats-grid">{stats.map(s=><div className="stat" key={s.label}><strong><CountUp value={s.value} suffix={s.suffix}/></strong><span>{s.label}</span></div>)}</Reveal><Reveal><div className="organized-head"><p className="eyebrow"><span>⌁</span> Built together</p><h3>Organized by four AWS Student Builder Groups</h3></div><div className="clubs-grid">{clubs.map((club,i)=><TiltCard className="club-card" key={club.name}><span className="club-index">0{i+1}</span><div className="club-mark">{club.initials}</div><h4>{club.name}</h4><p>{club.description}</p><Network /></TiltCard>)}</div></Reveal></div></section>; }

function PastEvents() { const imageMap={community:communityImage,workshop:workshopImage}; return <section id="events" className="section light-section"><div className="shell"><Reveal><SectionHeading light label="02 — Previously" title="The energy that" accent="brought us here." /></Reveal><div className="past-strip">{pastEvents.map((item,i)=><motion.article {...sectionMotion} transition={{...sectionMotion.transition,delay:i*.1}} className="past-card" key={item.title}><img src={imageMap[item.image as keyof typeof imageMap]} alt={`Students at ${item.title}`} loading="lazy" width="1408" height="912"/><div className="past-overlay"><span>{item.year}</span><h3>{item.title}</h3><p>{item.description}</p></div></motion.article>)}</div></div></section>; }

function Countdown() { const calc=()=>{const d=Math.max(0,new Date(event.dateISO).getTime()-Date.now());return [Math.floor(d/86400000),Math.floor(d/3600000)%24,Math.floor(d/60000)%60,Math.floor(d/1000)%60]}; const [time,setTime]=useState([0,0,0,0]); useEffect(()=>{setTime(calc());const t=setInterval(()=>setTime(calc()),1000);return()=>clearInterval(t)},[]); return <section className="countdown-band"><div className="countdown-cloud"><Cloud /></div><div className="shell countdown-layout"><div><p className="eyebrow"><span>⌁</span> Save your seat</p><h2>Event starts in</h2></div><div className="countdown">{time.map((n,i)=><div key={i}><strong>{String(n).padStart(2,"0")}</strong><span>{["Days","Hours","Minutes","Seconds"][i]}</span></div>)}</div><a className="button button-light" href={event.meetupUrl} target="_blank" rel="noreferrer">Register <ArrowRight /></a></div></section>; }

function Speakers() { return <section id="speakers" className="section speakers-section"><div className="shell"><Reveal className="heading-row"><SectionHeading label="03 — Voices worth hearing" title="Featured" accent="speakers." /><p>Builders, architects, and technical leaders will be announced here.</p></Reveal><div className="speakers-grid">{speakers.map((s,i)=><motion.div {...sectionMotion} transition={{...sectionMotion.transition,delay:(i%3)*.08}} key={s.name}><TiltCard className="speaker-card"><div className="portrait avatar-placeholder" role="img" aria-label={`Placeholder avatar for ${s.name}`}><UserRound/><span className="avatar-label">{s.name}</span><span className="speaker-number">0{i+1}</span></div><div className="speaker-info"><p>{s.role}</p><h3>{s.name}</h3><h4>“{s.talk}”</h4><div className="speaker-reveal"><p>{s.bio}</p><SocialLinks /></div></div></TiltCard></motion.div>)}</div></div></section>; }

function Schedule() { return <section id="schedule" className="section schedule-section"><div className="shell schedule-layout"><Reveal className="schedule-sticky"><SectionHeading label="04 — One remarkable day" title="The" accent="schedule." /><p>From your first coffee to the closing photo, every moment is built for learning and connection.</p><div className="schedule-note"><Clock3/><span>All times are Nepal Time<br/><b>UTC +05:45</b></span></div></Reveal><div className="timeline">{schedule.map((item,i)=><motion.article {...sectionMotion} transition={{...sectionMotion.transition,delay:.03*i}} className="timeline-item" key={`${item.time}-${item.title}`}><time>{item.time}</time><div className="timeline-node"><span/></div><div><span className={`track track-${item.tag.toLowerCase()}`}>{item.tag}</span><h3>{item.title}</h3><p>{item.speaker}</p></div></motion.article>)}</div></div></section>; }

function SpeakerCall() { return <section id="call-for-speakers" className="speaker-call"><div className="speaker-call-grid" aria-hidden="true"/><div className="shell call-layout"><Reveal><p className="eyebrow"><span>⌁</span> Call for speakers</p><h2>Your idea could<br/>change <em>someone’s path.</em></h2><p>We’re looking for honest stories, practical demos, hard-won lessons, and fresh perspectives from first-time and experienced speakers.</p><div className="topic-cloud">{["AWS","AI / ML","DevOps","Serverless","Security","Data","Careers"].map(x=><span key={x}>{x}</span>)}</div></Reveal><Reveal className="call-panel"><Code2/><p>Submissions close</p><strong>{event.speakerDeadline}</strong><a className="button button-primary" href={event.speakerFormUrl} target="_blank" rel="noreferrer">Apply as a speaker <ExternalLink /></a></Reveal></div></section>; }

function Partners() { return <section id="partners" className="section light-section partners-section"><div className="shell"><Reveal className="heading-row"><SectionHeading light label="05 — Powered by community" title="Partners in" accent="possibility." /><a href={event.partnerEmail} className="text-link">Become a partner <ArrowRight/></a></Reveal><div className="partner-groups">{partnerGroups.map((group,index)=><Reveal className={`partner-group ${index===0?"partner-group-featured":""}`} key={group.category}><p>{group.category}</p><div>{group.names.map(name=><span key={name}><Cloud/>{name}</span>)}</div></Reveal>)}</div></div></section>; }

function Team() { return <section id="team" className="section team-section"><div className="shell"><Reveal className="heading-row"><SectionHeading label="06 — The humans behind it" title="Meet the" accent="team." /><p>Four builder groups. One shared belief that world-class technology ecosystems can grow anywhere.</p></Reveal><div className="team-grid">{team.map((m,i)=><motion.article {...sectionMotion} transition={{...sectionMotion.transition,delay:(i%4)*.06}} key={m.name}><div className="team-portrait avatar-placeholder" role="img" aria-label={`Placeholder avatar for ${m.name}`}><UserRound/><span className="avatar-label">{m.name}</span></div><div><span>{m.club}</span><h3>{m.name}</h3><p>{m.role}</p><div className="team-social"><a href={socialLinks.linkedin} target="_blank" rel="noreferrer" aria-label={`${m.name} on LinkedIn`}><Linkedin/></a><a href={socialLinks.facebook} target="_blank" rel="noreferrer" aria-label={`${m.name} on Facebook`}><Facebook/></a><a href={socialLinks.instagram} target="_blank" rel="noreferrer" aria-label={`${m.name} on Instagram`}><Instagram/></a><a href={socialLinks.github} target="_blank" rel="noreferrer" aria-label={`${m.name} on GitHub`}><Github/></a></div></div></motion.article>)}</div></div></section>; }

function FAQs() { const [open,setOpen]=useState(0); return <section id="faqs" className="section faq-section"><div className="shell faq-layout"><Reveal><SectionHeading light label="07 — Good to know" title="Questions," accent="answered." /><p className="faq-aside">Still curious? Write to us at <a href={`mailto:${event.email}`}>{event.email}</a></p></Reveal><div className="faq-list">{faqs.map(([q,a],i)=><motion.div {...sectionMotion} className={`faq-item ${open===i?"open":""}`} key={q}><button onClick={()=>setOpen(open===i?-1:i)} aria-expanded={open===i}><span>{String(i+1).padStart(2,"0")}</span><strong>{q}</strong><ChevronDown/></button><AnimatePresence initial={false}>{open===i&&<motion.div initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}}><p>{a}</p></motion.div>}</AnimatePresence></motion.div>)}</div></div></section>; }

function MapSection() { return <section className="map-section"><div className="map-wrap"><iframe title="Map showing the event venue in Pokhara" src={event.mapEmbedUrl} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div><Reveal className="venue-card"><span className="venue-icon"><MapPin/></span><p className="eyebrow">Venue</p><h2>{event.venue}</h2><p>{event.address}</p><hr/><span className="landmark"><Mountain/>{event.landmark}</span><a className="button button-primary" href={event.directionsUrl} target="_blank" rel="noreferrer">Get directions <ExternalLink/></a></Reveal></section>; }

function Footer() { return <footer id="contact"><div className="footer-line"/><div className="shell footer-grid"><div className="footer-brand"><BrandMark/><p className="footer-desc">{footerContent.organizedBy}</p><div className="footer-social"><a href={socialLinks.linkedin} target="_blank" rel="noreferrer" aria-label="Visit LinkedIn"><Linkedin/></a><a href={socialLinks.github} target="_blank" rel="noreferrer" aria-label="Visit GitHub"><Github/></a><a href={socialLinks.facebook} target="_blank" rel="noreferrer" aria-label="Visit Facebook"><Facebook/></a><a href={socialLinks.instagram} target="_blank" rel="noreferrer" aria-label="Visit Instagram"><Instagram/></a></div></div><div className="footer-links"><h3>Quick Links</h3>{footerContent.quickLinks.map(([label,target])=>label==="Register"?<a key={label} href={event.meetupUrl} target="_blank" rel="noreferrer">Register</a>:<a key={label} href={`#${target}`}>{label}</a>)}</div><div className="footer-contact"><h3>Contact</h3><a href={`mailto:${event.email}`}><Mail/>{event.email}</a><span><MapPin/>{event.address}</span></div><div className="footer-coords"><h3>Coordinators</h3>{footerContent.coordinators.map(c=><a key={c.name} href={`tel:${c.phone.replace(/\s/g,"")}`}><Phone/><span>{c.name}<small>{c.phone}</small></span></a>)}</div><div className="footer-cta"><p>Ready to build beyond the clouds?</p><a className="button button-primary" href={event.meetupUrl} target="_blank" rel="noreferrer">Register now <ArrowRight/></a></div></div><div className="shell footer-bottom"><p>© 2026 AWS Student Community Day Pokhara. All rights reserved.</p><p>Designed with ♥ by {footerContent.designedBy}</p></div></footer>; }

export default function EventPage() { const {scrollYProgress}=useScroll(); const scaleX=useSpring(scrollYProgress,{stiffness:100,damping:25,restDelta:.001}); return <><motion.div className="progress-bar" style={{scaleX}}/><Navbar/><main><Hero/><About/><PastEvents/><Countdown/><Speakers/><Schedule/><SpeakerCall/><Partners/><Team/><FAQs/><MapSection/></main><Footer/></>; }
